source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/guang1472006/BOCe.git'

use_frameworks!

platform :ios, '9.0'

target 'BOCeApplicationManager' do

  pod 'BOCeApplicationManager', :git=> 'https://github.com/guang1472006/BOCeApplicationManager.git'
    
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
          end
      end
  end

end
